version: "2"

linters:
  default: none
  enable:
    - staticcheck
    - errcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
