linters:
  disable-all: true
  enable:
    - staticcheck
    - errcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
